### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by bas-sergii** [bas-sergii/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by SergiiKurinnyi** [comment]
The customer is studying Java for 6 months on various courses but didn't find the one yet. Hopefully, that going to change very soon.

**Comment by bas-sergii** [comment]
10x
