### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by bas-sergii** [bas-sergii/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by SergiiKurinnyi** [comment]
**Experience**

Ingenio d.o.o. / Private Entrepreneur
AUGUST 2014 - FEBRUARY 2019, SLOVENIA
⚫ An idea of creating a CMS for the hospitality industry resulted in opening an accommodation business
⚫ 9.0-9.2 Guest Review Awards by Booking.com in years 2016-2018
⚫ 3.88% conversion rate (1.66% area average) and 12.0% cancellations (24.4% area average)

Shop.ck.ua online store / Private Entrepreneur
MAY 2005 - APRIL 2015, UKRAINE
⚫ Created a new business with a very low budget and made it the main regional online seller.
⚫ Started from building a simple Web-page for the shop - to a powerful Internet Store with customer's personal page, SQL database, etc
⚫ Provided customers with a personal service: assembling hardware based on clients’ needs.
⚫ Consulting on various aspects of IT.


**Education**

Foxminded learning center / Java Spring
DECEMBER 2020 - PRESENT, ONLINE

Foxminded learning center / Java Tools
DECEMBER 2020, ONLINE

Cherkasy State Technological University / Philology (Applied Linguistics)
SEPTEMBER 2020 - PRESENT, UKRAINE

JavaRush online learning / Java Syntax & Java Core
SEPTEMBER 2020 - DECEMBER 2020, ONLINE

Cherkasy Bohdan Khmelnytsjyi National University / Romano-Germanic Philology (incomplete)
SEPTEMBER 2001 - DECEMBER 2005, UKRAINE
